const fs = require("fs");
const q = String.fromCharCode(39); // single quote

const content = [
  "import { Link } from " + q + "react-router-dom" + q,
  "",
  "const benefits = [",
  "  { icon: " + q + String.fromCodePoint(0x1FAC0) + q + ", title: " + q + "Wzmacnia serce" + q + ", desc: " + q + "Poprawia wydolno\u015B\u0107 uk\u0142adu kr\u0105\u017Cenia bez obci\u0105\u017Cania staw\u00F3w." + q + " },",
  "  { icon: " + q + String.fromCodePoint(0x1F9B5) + q + ", title: " + q + "\u0141agodzi b\u00F3le staw\u00F3w" + q + ", desc: " + q + "Woda odci\u0105\u017Ca stawy, u\u0142atwia ruch i zmniejsza b\u00F3l." + q + " },",
  "  { icon: " + q + String.fromCodePoint(0x1F4AA) + q + ", title: " + q + "Wzmacnia mi\u0119\u015Bnie" + q + ", desc: " + q + "Regularne \u0107wiczenia w wodzie poprawiaj\u0105 si\u0142\u0119 i kondycj\u0119." + q + " },",
  "  { icon: " + q + String.fromCodePoint(0x1F9D8) + q + ", title: " + q + "Poprawia r\u00F3wnowag\u0119" + q + ", desc: " + q + "Zmniejsza ryzyko upadk\u00F3w \u2013 kluczowe dla senior\u00F3w." + q + " },",
  "  { icon: " + q + String.fromCodePoint(0x1F60A) + q + ", title: " + q + "Poprawia nastr\u00F3j" + q + ", desc: " + q + "Ruch w grupie dodaje energii i redukuje stres." + q + " },",
  "  { icon: " + q + String.fromCodePoint(0x1F465) + q + ", title: " + q + "Zaj\u0119cia w grupie" + q + ", desc: " + q + "Integracja i wsp\u00F3lna motywacja w przyjaznej atmosferze." + q + " },",
  "]",
  "",
  "const galleryImages = [",
  "  { id: 1, src: " + q + "/images/gallery-1.jpg" + q + ", alt: " + q + "Zaj\u0119cia akwaaerobiki w basenie" + q + " },",
  "  { id: 2, src: " + q + "/images/gallery-2.jpg" + q + ", alt: " + q + "Seniorzy \u0107wicz\u0105 w wodzie" + q + " },",
  "  { id: 3, src: " + q + "/images/gallery-3.jpg" + q + ", alt: " + q + "Instruktorka prowadzi zaj\u0119cia" + q + " },",
  "  { id: 4, src: " + q + "/images/gallery-4.jpg" + q + ", alt: " + q + "Grupa senior\u00F3w w basenie" + q + " },",
  "  { id: 5, src: " + q + "/images/gallery-5.jpg" + q + ", alt: " + q + "\u0106wiczenia z przyrz\u0105dami" + q + " },",
  "  { id: 6, src: " + q + "/images/gallery-6.jpg" + q + ", alt: " + q + "U\u015Bmiechni\u0119ci uczestnicy" + q + " },",
  "  { id: 7, src: " + q + "/images/gallery-7.jpg" + q + ", alt: " + q + "Zaj\u0119cia w Basenie Fala" + q + " },",
  "]",
  "",
  "export default function HomePage() {",
  "  return (",
  '    <div className="space-y-8">',
  "      {/* Logo i tytu\u0142 */}",
  '      <section className="text-center py-4">',
  '        <div className="w-20 h-20 mx-auto mb-4 rounded-full bg-gradient-to-br from-teal-brand to-teal-light flex items-center justify-center shadow-lg">',
  '          <span className="text-white text-3xl font-bold">AL</span>',
  "        </div>",
  '        <h1 className="text-3xl font-bold text-teal-brand mb-1">Aqualady Aquaero</h1>',
  '        <p className="text-sm text-stone-500">Akwaaerobika dla senior\u00F3w w Warszawie</p>',
  "      </section>",
  "",
  "      {/* Hero Section */}",
  '      <section className="relative rounded-2xl overflow-hidden bg-gradient-to-br from-teal-brand/10 via-sand-light to-teal-brand/5 p-6 text-center">',
  '        <div className="absolute top-0 right-0 w-32 h-32 bg-teal-brand/5 rounded-full -translate-y-1/2 translate-x-1/2" />',
  '        <div className="absolute bottom-0 left-0 w-24 h-24 bg-sand/20 rounded-full translate-y-1/2 -translate-x-1/2" />',
  '        <div className="relative z-10">',
  '          <h2 className="text-lg font-semibold text-teal-brand mb-2">',
  "            Ruch to zdrowie \u2013 w wodzie to przyjemno\u015B\u0107!",
  "          </h2>",
  '          <p className="text-sm text-stone-600 mb-4 leading-relaxed">',
  "            Zapraszamy senior\u00F3w na zaj\u0119cia akwaaerobiki w dw\u00F3ch basenach w Warszawie.",
  "            \u0106wiczenia w wodzie s\u0105 bezpieczne, skuteczne i dostosowane do mo\u017Cliwo\u015Bci",
  "            ka\u017Cdego uczestnika. Popraw swoj\u0105 kondycj\u0119, zrelaksuj si\u0119 i poznaj nowych przyjaci\u00F3\u0142!",
  "          </p>",
  "          <Link",
  '            to="/booking"',
  '            className="inline-block bg-teal-brand text-white font-bold text-base px-8 py-3.5 rounded-xl shadow-lg hover:bg-teal-light active:scale-95 transition-all"',
  "          >",
  "            Kup karnet",
  "          </Link>",
  "        </div>",
  "      </section>",
  "",
  "      {/* Benefits */}",
  "      <section>",
  '        <h2 className="text-lg font-bold text-stone-800 mb-3 flex items-center gap-2">',
  '          <span className="w-1 h-5 bg-teal-brand rounded-full inline-block" />',
  "          Dlaczego akwaaerobika?",
  "        </h2>",
  '        <div className="grid grid-cols-2 gap-3">',
  "          {benefits.map((b, i) => (",
  '            <div key={i} className="bg-white rounded-xl p-3.5 shadow-sm border border-sand/20 hover:shadow-md transition-shadow">',
  '              <span className="text-2xl block mb-1.5">{b.icon}</span>',
  '              <h3 className="text-sm font-semibold text-stone-800 mb-0.5">{b.title}</h3>',
  '              <p className="text-[11px] text-stone-500 leading-snug">{b.desc}</p>',
  "            </div>",
  "          ))}",
  "        </div>",
  "      </section>",
  "",
  "      {/* About */}",
  '      <section className="bg-white rounded-2xl p-5 shadow-sm border border-sand/20">',
  '        <h2 className="text-lg font-bold text-stone-800 mb-3 flex items-center gap-2">',
  '          <span className="w-1 h-5 bg-sand-dark rounded-full inline-block" />',
  "          O nas",
  "        </h2>",
  '        <p className="text-sm text-stone-600 leading-relaxed">',
  '          Aqualady Aquaero zaprasza senior\u00F3w na zdrowe, poranne zaj\u0119cia w Warszawie. Nasza akwaaerobika poprawia sprawno\u015B\u0107 staw\u00F3w i dodaje energii bez nadmiernego obci\u0105\u017Cenia organizmu. To idealny spos\u00F3b na zachowanie aktywno\u015Bci fizycznej oraz spotkanie nowych os\u00F3b w przyjaznej atmosferze. Wybierz sw\u00F3j basen, zarezerwuj dogodne terminy w kalendarzu i do\u0142\u0105cz do naszej spo\u0142eczno\u015Bci ju\u017C dzi\u015B. Poczuj si\u0119 m\u0142odziej z nami!',
  "        </p>",
  "      </section>",
  "",
  "      {/* Gallery */}",
  "      <section>",
  '        <h2 className="text-lg font-bold text-stone-800 mb-3 flex items-center gap-2">',
  '          <span className="w-1 h-5 bg-teal-brand rounded-full inline-block" />',
  "          Galeria",
  "        </h2>",
  '        <div className="grid grid-cols-3 gap-2">',
  "          {galleryImages.slice(0, 5).map((img) => (",
  "            <div",
  "              key={img.id}",
  '              className={`bg-sand-light rounded-xl overflow-hidden aspect-square flex items-center justify-center text-stone-400 text-[10px] text-center p-1 border border-sand/20 ${',
  "                img.id === 1 ? " + q + "col-span-2 row-span-2" + q + " : " + q + q,
  "              }`}",
  "            >",
  '              <div className="w-full h-full flex flex-col items-center justify-center">',
  '                <svg className="w-6 h-6 mb-1 opacity-40" fill="none" stroke="currentColor" viewBox="0 0 24 24">',
  '                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />',
  "                </svg>",
  "                <span>Zdj\u0119cie {img.id}</span>",
  "              </div>",
  "            </div>",
  "          ))}",
  "        </div>",
  "        {galleryImages.length > 5 && (",
  '          <div className="grid grid-cols-3 gap-2 mt-2">',
  "            {galleryImages.slice(5).map((img) => (",
  "              <div",
  "                key={img.id}",
  '                className="bg-sand-light rounded-xl overflow-hidden aspect-square flex items-center justify-center text-stone-400 text-[10px] text-center p-1 border border-sand/20"',
  "              >",
  '                <div className="w-full h-full flex flex-col items-center justify-center">',
  '                  <svg className="w-6 h-6 mb-1 opacity-40" fill="none" stroke="currentColor" viewBox="0 0 24 24">',
  '                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />',
  "                  </svg>",
  "                  <span>Zdj\u0119cie {img.id}</span>",
  "                </div>",
  "              </div>",
  "            ))}",
  "          </div>",
  "        )}",
  "      </section>",
  "",
  "      {/* CTA Button */}",
  '      <section className="text-center pb-4">',
  "        <Link",
  '          to="/booking"',
  '          className="inline-block bg-teal-brand text-white font-bold text-base px-10 py-4 rounded-xl shadow-lg hover:bg-teal-light active:scale-95 transition-all w-full"',
  "        >",
  "          Kup karnet",
  "        </Link>",
  "      </section>",
  "    </div>",
  "  )",
  "}",
  ""
].join("\n");

fs.writeFileSync("src/pages/HomePage.tsx", content, "utf8");
console.log("OK - HomePage.tsx written, length:", content.length);
